import redis
version: "3"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped

r = redis.Redis(host="redis", port=6379, decode_responses=True)
